### PR TITLE
Update deps and remove support of old Node.js versions

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Ref: #13

> Is there anything in the PR that needs further explanation?

~~This change updates all the dependencies except for `execa`.~~
**This change includes the `execa` update and drops the support of old Node.js versions.**

The latest version of `execa` breaks `engines.node`, which does not match our `engines.node`.

```console
$ npm view create-stylelint engines.node
^14.13.1 || >=16.0.0 || >=18.0.0

$ npm view 'execa@6.1.0' engines.node
^12.20.0 || ^14.13.1 || >=16.0.0

$ npm view 'execa@7.0.0' engines.node
^14.18.0 || ^16.14.0 || >=18.0.0
```

See also:

```console
$ npm outdated
Package  Current  Wanted  Latest  Location            Depended by
execa      6.1.0   6.1.0   7.0.0  node_modules/execa  create-stylelint
```

### CODE REVIEW

**Comment by jeddy3** [comment]
Let's bump our engines to `^14.18.0 || ^16.14.0 || >=18.0.0` and update `exec` while we are pre-`1.0.0`.

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you!

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for the super-fast review! I'll release `0.2.0` after merging.

**Comment by ybiquitous** [comment]
`0.2.0` is out! 🎉 

- https://github.com/stylelint/create-stylelint/releases/tag/v0.2.0
- https://www.npmjs.com/package/create-stylelint

**Comment by ybiquitous** [comment]
Oops. `v` prefix is accidentally appended to the tag (`v0.2.0`). Why? 🤔

**Comment by ybiquitous** [comment]
Ah, I got it. We have to add `.npmrc` including `tag-version-prefix = ""`:

https://github.com/stylelint/stylelint/blob/4835d16d08fd91ff9e0ab47c1f7adbcf73fb0342/.npmrc#L1

**Comment by ybiquitous** [comment]
Now I try removing `v` prefix from `v0.2.0`.

**Comment by ybiquitous** [comment]
I have successfully updated the tag: https://github.com/stylelint/create-stylelint/releases/tag/0.2.0

**Comment by ybiquitous** [comment]
And I added `.npmrc` via f1262d8.

**Pull request merged**
